# This rule is not used by the project sandboxd-controlplane itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.sandboxd.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sandboxd-controlplane
    app.kubernetes.io/managed-by: kustomize
  name: sandboxtemplate-admin-role
rules:
- apiGroups:
  - core.sandboxd.io
  resources:
  - sandboxtemplates
  verbs:
  - '*'
- apiGroups:
  - core.sandboxd.io
  resources:
  - sandboxtemplates/status
  verbs:
  - get
